#!/bin/bash

# Setup script for Widget & Menu Bar Integration
# This script adds files to Xcode project and creates necessary structure

echo "🚀 Cloutmate Widget & Menu Bar Setup"
echo "===================================="
echo ""

# Check if we're in the right directory
if [ ! -f "Cloutmate.xcodeproj/project.pbxproj" ]; then
    echo "❌ Error: This script must be run from the Cloutmate project root"
    exit 1
fi

echo "✅ Found Cloutmate.xcodeproj"
echo ""
echo "Manual steps required in Xcode:"
echo "================================="
echo ""
echo "1️⃣  CREATE SHARED FRAMEWORK TARGET"
echo "   - File > New > Target"
echo "   - macOS > Framework"
echo "   - Name: CloutmateShared"
echo "   - Bundle ID: com.kosmicapps.Cloutmate.CloutmateShared"
echo "   - Team: Your team"
echo "   - Click Finish"
echo ""
echo "2️⃣  CREATE WIDGET EXTENSION TARGET"
echo "   - File > New > Target"
echo "   - macOS > Widget Extension"
echo "   - Name: CloutmateWidget"
echo "   - Bundle ID: com.kosmicapps.Cloutmate.CloutmateWidget"
echo "   - Include Configuration Intent: NO"
echo "   - Team: Your team"
echo "   - Click Finish"
echo ""
echo "3️⃣  CREATE MENU BAR APP TARGET"
echo "   - File > New > Target"
echo "   - macOS > App"
echo "   - Name: CloutmateMenuBar"
echo "   - Bundle ID: com.kosmicapps.Cloutmate.CloutmateMenuBar"
echo "   - Language: Swift"
echo "   - Team: Your team"
echo "   - Click Finish"
echo ""
echo "4️⃣  ADD APP GROUP ENTITLEMENT TO MAIN APP"
echo "   - Select Cloutmate target"
echo "   - Go to Signing & Capabilities tab"
echo "   - Click + Capability"
echo "   - Add 'App Groups'"
echo "   - Add group: group.kosmicapps.cloutmate"
echo "   - Enable 'iCloud' capability with CloudKit"
echo ""
echo "5️⃣  ADD APP GROUP TO SHARED FRAMEWORK"
echo "   - Select CloutmateShared target"
echo "   - Go to Signing & Capabilities tab"
echo "   - Click + Capability"
echo "   - Add 'App Groups'"
echo "   - Add group: group.kosmicapps.cloutmate"
echo ""
echo "6️⃣  ADD APP GROUP TO WIDGET"
echo "   - Select CloutmateWidget target"
echo "   - Go to Signing & Capabilities tab"
echo "   - Click + Capability"
echo "   - Add 'App Groups'"
echo "   - Add group: group.kosmicapps.cloutmate"
echo ""
echo "7️⃣  ADD APP GROUP TO MENU BAR APP"
echo "   - Select CloutmateMenuBar target"
echo "   - Go to Signing & Capabilities tab"
echo "   - Click + Capability"
echo "   - Add 'App Groups'"
echo "   - Add group: group.kosmicapps.cloutmate"
echo "   - Add 'App Sandbox' capability"
echo "   - Enable 'Outgoing Connections'"
echo ""
echo "8️⃣  ADD FILES TO TARGETS"
echo "   For CloutmateShared:"
echo "   - Add CloutmateShared/CloutmateShared/Models/*.swift"
echo "   - Add CloutmateShared/CloutmateShared/Services/*.swift"
echo "   - Add CloutmateShared/CloutmateShared/UI/*.swift"
echo "   - Add CloutmateShared/CloutmateShared/SharedDataManager.swift"
echo ""
echo "   For CloutmateWidget:"
echo "   - Add CloutmateWidget/*.swift"
echo ""
echo "   For CloutmateMenuBar:"
echo "   - Add CloutmateMenuBar/*.swift"
echo ""
echo "9️⃣  CONFIGURE MENU BAR AS AGENT APP"
echo "   - Select CloutmateMenuBar target"
echo "   - Go to Info tab"
echo "   - Add new key: LSUIElement"
echo "   - Set value: YES (to hide from Dock)"
echo ""
echo "🔟  UPDATE MAIN APP TO USE SHARED CONTAINER"
echo "   - Open Cloutmate/CloutmateApp.swift"
echo "   - Update sharedModelContainer to use SharedDataManager"
echo ""
echo "✅ When done, run: xcodebuild -project Cloutmate.xcodeproj"
echo ""
echo "Files are ready in:"
echo "  - CloutmateShared/CloutmateShared/"
echo "  - CloutmateWidget/"
echo "  - CloutmateMenuBar/"
echo ""

