#!/bin/bash

# Setup script for Widget & Menu Bar Integration
# This script adds files to Xcode project and creates necessary structure

echo "🚀 FocusOS Widget & Menu Bar Setup"
echo "===================================="
echo ""

# Check if we're in the right directory
if [ ! -f "FocusOS.xcodeproj/project.pbxproj" ]; then
    echo "❌ Error: This script must be run from the FocusOS project root"
    exit 1
fi

echo "✅ Found FocusOS.xcodeproj"
echo ""
echo "Manual steps required in Xcode:"
echo "================================="
echo ""
echo "1️⃣  CREATE SHARED FRAMEWORK TARGET"
echo "   - File > New > Target"
echo "   - macOS > Framework"
echo "   - Name: FocusOSShared"
echo "   - Bundle ID: com.kosmicapps.FocusOS.FocusOSShared"
echo "   - Team: Your team"
echo "   - Click Finish"
echo ""
echo "2️⃣  CREATE WIDGET EXTENSION TARGET"
echo "   - File > New > Target"
echo "   - macOS > Widget Extension"
echo "   - Name: FocusOSWidget"
echo "   - Bundle ID: com.kosmicapps.FocusOS.FocusOSWidget"
echo "   - Include Configuration Intent: NO"
echo "   - Team: Your team"
echo "   - Click Finish"
echo ""
echo "3️⃣  CREATE MENU BAR APP TARGET"
echo "   - File > New > Target"
echo "   - macOS > App"
echo "   - Name: FocusOSMenuBar"
echo "   - Bundle ID: com.kosmicapps.FocusOS.FocusOSMenuBar"
echo "   - Language: Swift"
echo "   - Team: Your team"
echo "   - Click Finish"
echo ""
echo "4️⃣  ADD APP GROUP ENTITLEMENT TO MAIN APP"
echo "   - Select FocusOS target"
echo "   - Go to Signing & Capabilities tab"
echo "   - Click + Capability"
echo "   - Add 'App Groups'"
echo "   - Add group: group.kosmicapps.focusos"
echo "   - Enable 'iCloud' capability with CloudKit"
echo ""
echo "5️⃣  ADD APP GROUP TO SHARED FRAMEWORK"
echo "   - Select FocusOSShared target"
echo "   - Go to Signing & Capabilities tab"
echo "   - Click + Capability"
echo "   - Add 'App Groups'"
echo "   - Add group: group.kosmicapps.focusos"
echo ""
echo "6️⃣  ADD APP GROUP TO WIDGET"
echo "   - Select FocusOSWidget target"
echo "   - Go to Signing & Capabilities tab"
echo "   - Click + Capability"
echo "   - Add 'App Groups'"
echo "   - Add group: group.kosmicapps.focusos"
echo ""
echo "7️⃣  ADD APP GROUP TO MENU BAR APP"
echo "   - Select FocusOSMenuBar target"
echo "   - Go to Signing & Capabilities tab"
echo "   - Click + Capability"
echo "   - Add 'App Groups'"
echo "   - Add group: group.kosmicapps.focusos"
echo "   - Add 'App Sandbox' capability"
echo "   - Enable 'Outgoing Connections'"
echo ""
echo "8️⃣  ADD FILES TO TARGETS"
echo "   For FocusOSShared:"
echo "   - Add FocusOSShared/FocusOSShared/Models/*.swift"
echo "   - Add FocusOSShared/FocusOSShared/Services/*.swift"
echo "   - Add FocusOSShared/FocusOSShared/UI/*.swift"
echo "   - Add FocusOSShared/FocusOSShared/SharedDataManager.swift"
echo ""
echo "   For FocusOSWidget:"
echo "   - Add FocusOSWidget/*.swift"
echo ""
echo "   For FocusOSMenuBar:"
echo "   - Add FocusOSMenuBar/*.swift"
echo ""
echo "9️⃣  CONFIGURE MENU BAR AS AGENT APP"
echo "   - Select FocusOSMenuBar target"
echo "   - Go to Info tab"
echo "   - Add new key: LSUIElement"
echo "   - Set value: YES (to hide from Dock)"
echo ""
echo "🔟  UPDATE MAIN APP TO USE SHARED CONTAINER"
echo "   - Open FocusOS/FocusOSApp.swift"
echo "   - Update sharedModelContainer to use SharedDataManager"
echo ""
echo "✅ When done, run: xcodebuild -project FocusOS.xcodeproj"
echo ""
echo "Files are ready in:"
echo "  - FocusOSShared/FocusOSShared/"
echo "  - FocusOSWidget/"
echo "  - FocusOSMenuBar/"
echo ""

