//
//  AdaptiveJournalService.swift
//  FocusOS
//
//  Auto-generates weekly journal entries based on actions
//

import Foundation
import SwiftData
import os.log

@MainActor
final class AdaptiveJournalService {
    static let shared = AdaptiveJournalService()
    
    private let logger = Logger(subsystem: "com.kosmicapps.FocusOS", category: "AdaptiveJournal")
    
    private init() {}
    
    /// Generate weekly auto-entry
    func generateWeeklyEntry(
        endDate: Date = Date(),
        modelContext: ModelContext
    ) async throws -> Journal {
        let calendar = Calendar.current
        guard let startDate = calendar.date(byAdding: .day, value: -7, to: endDate) else {
            throw AdaptiveJournalError.invalidDateRange
        }
        
        // Gather data
        let snapshot = await AnalyticsEngine.shared.generateSnapshot(
            for: .thisWeek,
            modelContext: modelContext
        )
        
        let narrativeSummary = NarrativeEngine.shared.generateNarrativeSummary(modelContext: modelContext)
        
        // Generate content
        let content = buildJournalContent(
            snapshot: snapshot,
            narrative: narrativeSummary,
            dateRange: DateInterval(start: startDate, end: endDate)
        )
        
        // Create journal entry
        let journal = Journal(
            title: "Weekly Reflection - \(formatDate(endDate))",
            content: content,
            entryDate: endDate,
            entryType: .reflection
        )
        
        // Mark as auto-generated (extend Journal model)
        // journal.isAutoGenerated = true
        
        modelContext.insert(journal)
        
        do {
            try modelContext.save()
            logger.info("Generated weekly adaptive journal entry")
            return journal
        } catch {
            logger.error("Failed to save journal entry: \(error.localizedDescription)")
            throw AdaptiveJournalError.saveFailed
        }
    }
    
    private func buildJournalContent(
        snapshot: AnalyticsSnapshot,
        narrative: NarrativeSummaryContext?,
        dateRange: DateInterval
    ) -> String {
        var content = "# Weekly Reflection\n\n"
        content += "**Period:** \(formatDate(dateRange.start)) - \(formatDate(dateRange.end))\n\n"
        
        if let narrative = narrative {
            content += "## Overview\n\n"
            content += narrative.keyInsight ?? "This week brought steady progress.\n\n"
            
            if !narrative.keyThemes.isEmpty {
                content += "## Key Themes\n\n"
                for theme in narrative.keyThemes {
                    content += "- \(theme)\n"
                }
                content += "\n"
            }
        }
        
        // Add focus stats
        if snapshot.focusSessionsCount > 0 {
            content += "## Focus\n\n"
            content += "Completed \(snapshot.focusSessionsCount) focus sessions.\n\n"
        }
        
        // Add emotional tone
        content += "## Emotional Tone\n\n"
        content += "\(snapshot.emotionalSnapshot.valence > 0 ? "Positive" : snapshot.emotionalSnapshot.valence < 0 ? "Challenging" : "Balanced") energy this week.\n\n"
        
        return content
    }
    
    private func formatDate(_ date: Date) -> String {
        let formatter = DateFormatter()
        formatter.dateStyle = .medium
        return formatter.string(from: date)
    }
}

enum AdaptiveJournalError: LocalizedError {
    case invalidDateRange
    case saveFailed
    
    var errorDescription: String? {
        switch self {
        case .invalidDateRange:
            return "Invalid date range for journal entry"
        case .saveFailed:
            return "Failed to save journal entry"
        }
    }
}

