//
//  FocusForecast.swift
//  FocusOS
//
//  Phase 9: Predictive Reflection Engine
//  Stores anticipatory cognitive state forecasts generated by CognitionPredictor
//

import Foundation
import SwiftData

/// Overall energy trajectory predicted for the upcoming focus horizon.
enum FocusEnergyTrend: String, Codable, CaseIterable, Sendable {
    case rising
    case stable
    case declining

    var displayName: String {
        switch self {
        case .rising: return "Rising"
        case .stable: return "Stable"
        case .declining: return "Declining"
        }
    }
}

/// SwiftData model representing a predictive cognition forecast window.
@Model
final class FocusForecast {
    @Attribute(.unique) var id: UUID

    /// When the forecast was generated.
    var generatedAt: Date

    /// Start of the time horizon the forecast applies to.
    var horizonStart: Date

    /// End of the time horizon the forecast applies to.
    var horizonEnd: Date

    /// Calculated risk of fatigue during the horizon (0 - 1).
    var fatigueRisk: Double

    /// Stability of focus momentum (0 - 1, higher = steadier).
    var focusStability: Double

    /// Raw backing storage for the energy trend enum.
    private(set) var energyTrendRaw: String

    /// Recommended tone for next nudges/interactions.
    private(set) var toneRecommendationRaw: String

    /// Recommended confidence for taking action on this forecast (0 - 1).
    var confidence: Double

    /// Optional accuracy score once validated (0 - 1).
    var predictionAccuracy: Double?

    /// When the next focus peak begins (if known).
    var nextFocusWindowStart: Date?

    /// When the next focus peak ends (if known).
    var nextFocusWindowEnd: Date?

    /// Auxiliary metadata for downstream services (JSON-friendly key/value pairs).
    var metadata: [String: String]

    init(
        horizonStart: Date,
        horizonEnd: Date,
        fatigueRisk: Double,
        focusStability: Double,
        energyTrend: FocusEnergyTrend,
        toneRecommendation: EmotionalState,
        confidence: Double,
        nextFocusWindowStart: Date? = nil,
        nextFocusWindowEnd: Date? = nil,
        metadata: [String: String] = [:]
    ) {
        self.id = UUID()
        self.generatedAt = Date()
        self.horizonStart = horizonStart
        self.horizonEnd = horizonEnd
        self.fatigueRisk = min(max(fatigueRisk, 0.0), 1.0)
        self.focusStability = min(max(focusStability, 0.0), 1.0)
        self.energyTrendRaw = energyTrend.rawValue
        self.toneRecommendationRaw = toneRecommendation.rawValue
        self.confidence = min(max(confidence, 0.0), 1.0)
        self.predictionAccuracy = nil
        self.nextFocusWindowStart = nextFocusWindowStart
        self.nextFocusWindowEnd = nextFocusWindowEnd
        self.metadata = metadata
    }

    var energyTrend: FocusEnergyTrend {
        get { FocusEnergyTrend(rawValue: energyTrendRaw) ?? .stable }
        set { energyTrendRaw = newValue.rawValue }
    }

    var toneRecommendation: EmotionalState {
        get { EmotionalState(rawValue: toneRecommendationRaw) ?? .calm }
        set { toneRecommendationRaw = newValue.rawValue }
    }

    /// Convenience DateInterval representation for the forecast horizon.
    var forecastHorizon: DateInterval {
        DateInterval(start: horizonStart, end: horizonEnd)
    }

    /// Optional DateInterval describing the next predicted focus window.
    var nextFocusWindow: DateInterval? {
        guard let start = nextFocusWindowStart, let end = nextFocusWindowEnd else {
            return nil
        }
        return DateInterval(start: start, end: end)
    }

    /// Update forecast accuracy after observing actual outcomes.
    func recordAccuracy(_ accuracy: Double) {
        predictionAccuracy = min(max(accuracy, 0.0), 1.0)
    }
}

